services:
  - type: web
    name: zombie-dnd-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DATABASE_URL
        value: "postgresql://zombie_db_ygt2_user:wwlSORNlTIZftgtEGGvbWnIJ4Veyq0rt@dpg-d0uu13adbo4c73bm9qj0-a/zombie_db_ygt2"
